---
- name: Install Site24x7 Full Stack Agent
  hosts: hostname          ##Change this value to select desired hosts
  remote_user: root

  vars:
     device_key: ""             ##Device key obtained from your Site24x7 portal (required). Refer: https://www.site24x7.com/help/admin/developer/device-key.html
     proxy: ""                  ##Proxy if required (leave empty for none). Refer: https://support.site24x7.com/portal/en/kb/articles/how-do-i-configure-proxy-for-linux-agent-during-installation
     agent_type: infra          ##Agent type like fso or infra (leave for defaults)
     custom_args: ""            ##Any additional install arguments to append (leave for defaults)

  tasks:
     - name: Check if Site24x7 Full Stack Agent is already installed
       stat:
         path: /opt/site24x7/monagent
       register: installed

     - name: Download Site24x7 Full Stack Agent installer (x86_64)
       get_url:
         url: https://staticdownloads.site24x7.com/server/Site24x7FullStackAgent_x64Linux.install
         dest: /opt/Site24x7FullStackAgent_x64Linux.install
         mode: 0750
       when: ansible_machine == "x86_64" and not installed.stat.exists
     - name: Install Site24x7 Full Stack Agent (x86_64)
       shell: /opt/Site24x7FullStackAgent_x64Linux.install -i -key={{ device_key }} -installer=ansible -automation=true -agent_type={{ agent_type }} {{ ('-proxy=' + proxy) if proxy else '' }} {{ custom_args }}
       when: ansible_machine == "x86_64" and not installed.stat.exists

     - name: Download Site24x7 Full Stack Agent installer (i386)
       get_url:
         url: https://staticdownloads.site24x7.com/server/Site24x7FullStackAgent_x86Linux.install
         dest: /opt/Site24x7FullStackAgent_x86Linux.install
         mode: 0750
       when: ansible_machine == "i386" and not installed.stat.exists
     - name: Install Site24x7 Full Stack Agent (i386)
       shell: /opt/Site24x7FullStackAgent_x86Linux.install -i -key={{ device_key }} -installer=ansible -automation=true -agent_type={{ agent_type }} {{ ('-proxy=' + proxy) if proxy else '' }} {{ custom_args }}
       when: ansible_machine == "i386" and not installed.stat.exists

     - name: Download Site24x7 Full Stack Agent installer (aarch64)
       get_url:
         url: https://staticdownloads.site24x7.com/server/arm/Site24x7FullStackAgent_x64Linux.install
         dest: /opt/Site24x7FullStackAgent_x64Linux.install
         mode: 0750
       when: ansible_machine == "aarch64" and not installed.stat.exists
     - name: Install Site24x7 Full Stack Agent (aarch64)
       shell: /opt/Site24x7FullStackAgent_x64Linux.install -i -key={{ device_key }} -installer=ansible -automation=true -agent_type={{ agent_type }} {{ ('-proxy=' + proxy) if proxy else '' }} {{ custom_args }}
       when: ansible_machine == "aarch64" and not installed.stat.exists

     - name: Restart Site24x7 Full Stack Agent service
       service:
         name: site24x7monagent
         state: restarted
       when: ansible_machine in ["x86_64", "i386", "aarch64"] and not installed.stat.exists

     - name: Remove Site24x7 Full Stack Agent installer (x86_64/aarch64)
       file:
         state: absent
         path: /opt/Site24x7FullStackAgent_x64Linux.install
       when: (ansible_machine == "x86_64" or ansible_machine == "aarch64") and not installed.stat.exists
     - name: Remove Site24x7 Full Stack Agent installer (i386)
       file:
         state: absent
         path: /opt/Site24x7FullStackAgent_x86Linux.install
       when: ansible_machine == "i386"
